// <auto-generated />
using System;
using DadosPublicosReceita.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DadosPublicosReceita.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250205142717_AtualizarRelacionamentosEstabelecimentos")]
    partial class AtualizarRelacionamentosEstabelecimentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Cnae", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(7)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("Cnae", (string)null);
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Empresa", b =>
                {
                    b.Property<string>("CnpjBasico")
                        .HasMaxLength(8)
                        .HasColumnType("CHAR");

                    b.Property<decimal>("CapitalSocial")
                        .HasPrecision(18, 4)
                        .HasColumnType("MONEY");

                    b.Property<string>("EnteFederativoResp")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("NaturezaJuridica")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("CHAR");

                    b.Property<int>("PorteEmpresa")
                        .HasColumnType("INT");

                    b.Property<string>("QualificacaoResponsavel")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("CnpjBasico");

                    b.HasIndex(new[] { "RazaoSocial" }, "IX_Empresa_RazaoSocial");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("CHAR");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("EstabelecimentoCnpjBasico")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("CHAR")
                        .HasColumnName("EstabelecimentoId");

                    b.Property<string>("EstabelecimentoCnpjDv")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR");

                    b.Property<string>("EstabelecimentoCnpjOrdem")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("CHAR");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("TipoLogradouro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoCnpjBasico", "EstabelecimentoCnpjOrdem", "EstabelecimentoCnpjDv")
                        .IsUnique();

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Estabelecimento", b =>
                {
                    b.Property<string>("CnpjBasico")
                        .HasMaxLength(8)
                        .HasColumnType("CHAR");

                    b.Property<string>("CnpjOrdem")
                        .HasMaxLength(4)
                        .HasColumnType("CHAR");

                    b.Property<string>("CnpjDv")
                        .HasMaxLength(2)
                        .HasColumnType("CHAR");

                    b.Property<string>("CnaePrincipalId")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("VARCHAR");

                    b.Property<DateOnly>("DataInicioAtividade")
                        .HasColumnType("DATE");

                    b.Property<DateOnly>("DataSituacaoCadastral")
                        .HasColumnType("DATE");

                    b.Property<DateOnly?>("DataSituacaoEspecial")
                        .HasColumnType("DATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("EmpresaId")
                        .HasColumnType("CHAR(8)");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivoSituacaoCadastral")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<byte>("SituacaoCadastral")
                        .HasColumnType("TINYINT");

                    b.Property<string>("SituacaoEspecial")
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR");

                    b.Property<byte>("TipoDoEstabelecimento")
                        .HasColumnType("TINYINT");

                    b.HasKey("CnpjBasico", "CnpjOrdem", "CnpjDv")
                        .HasName("PK_Estabelecimento");

                    b.HasIndex("CnaePrincipalId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Estabelecimento", (string)null);
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Municipio", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(4)
                        .HasColumnType("CHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("Municipio", (string)null);
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Pais", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .HasColumnType("CHAR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Codigo");

                    b.ToTable("Pais", (string)null);
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("EstabelecimentoCnpjBasico")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("CHAR")
                        .HasColumnName("EstabelecimentoId");

                    b.Property<string>("EstabelecimentoCnpjDv")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("CHAR");

                    b.Property<string>("EstabelecimentoCnpjOrdem")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("CHAR");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("TelefoneCompleto")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Numero");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoCnpjBasico", "EstabelecimentoCnpjOrdem", "EstabelecimentoCnpjDv");

                    b.ToTable("Telefone", null, t =>
                        {
                            t.Property("Numero")
                                .HasColumnName("Numero1");
                        });
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("DadosPublicosReceita.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithOne("Endereco")
                        .HasForeignKey("DadosPublicosReceita.Domain.Entities.Endereco", "EstabelecimentoCnpjBasico", "EstabelecimentoCnpjOrdem", "EstabelecimentoCnpjDv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Estabelecimento", b =>
                {
                    b.HasOne("DadosPublicosReceita.Domain.Entities.Cnae", "CnaePrincipal")
                        .WithMany()
                        .HasForeignKey("CnaePrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DadosPublicosReceita.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Estabelecimentos")
                        .HasForeignKey("EmpresaId");

                    b.Navigation("CnaePrincipal");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Telefone", b =>
                {
                    b.HasOne("DadosPublicosReceita.Domain.Entities.Estabelecimento", "Estabelecimento")
                        .WithMany("Telefones")
                        .HasForeignKey("EstabelecimentoCnpjBasico", "EstabelecimentoCnpjOrdem", "EstabelecimentoCnpjDv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estabelecimento");
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Estabelecimentos");
                });

            modelBuilder.Entity("DadosPublicosReceita.Domain.Entities.Estabelecimento", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
